---
abstract: 'cPanel fork of JSON::XS, fast and correct serializing'
author:
  - 'Reini Urban <rurban@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.3, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Cpanel-JSON-XS
no_index:
  directory:
    - t
    - inc
requires:
  Pod::Text: '2.08'
resources:
  bugtracker: https://github.com/rurban/Cpanel-JSON-XS/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/rurban/Cpanel-JSON-XS
version: '3.0239'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
