source "https://rubygems.org"


gem "sinatra"
gem "mysql2"
gem "mysql2-cs-bind"
gem "erubis"
gem "unicorn"

gem 'redis'
gem 'puma'

group :development do
  gem 'foreman'
  gem 'sinatra-contrib', require: nil

  gem 'rack-lineprof'
  gem 'rack-mini-profiler'
  gem 'stackprof'

  # For memory profiling (requires Ruby MRI 2.1+)
  gem 'memory_profiler'

  # For call-stack profiling flamegraphs (requires Ruby MRI 2.0.0+)
  gem 'flamegraph'
  gem 'stackprof'     # For Ruby MRI 2.1+
  gem 'fast_stack'    # For Ruby MRI 2.0
end

