---
abstract: 'the distribution metadata for a CPAN dist'
author:
  - 'David Golden <dagolden@cpan.org>'
  - 'Ricardo Signes <rjbs@cpan.org>'
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  Data::Dumper: '0'
  ExtUtils::MakeMaker: '0'
  File::Basename: '0'
  File::Spec: '0.80'
  File::Spec::Functions: '0'
  File::Temp: '0.20'
  IO::Dir: '0'
  JSON::PP: '2.27300'
  Storable: '0'
  Test::More: '0.88'
  lib: '0'
  overload: '0'
  perl: '5.008001'
  utf8: '0'
  vars: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
  perl: '5.008001'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.007, CPAN::Meta::Converter version 2.150009'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CPAN-Meta
no_index:
  directory:
    - corpus
    - examples
    - history
    - t
    - xt
  package:
    - DB
provides:
  CPAN::Meta:
    file: lib/CPAN/Meta.pm
    version: '2.150010'
  CPAN::Meta::Converter:
    file: lib/CPAN/Meta/Converter.pm
    version: '2.150010'
  CPAN::Meta::Feature:
    file: lib/CPAN/Meta/Feature.pm
    version: '2.150010'
  CPAN::Meta::History:
    file: lib/CPAN/Meta/History.pm
    version: '2.150010'
  CPAN::Meta::Merge:
    file: lib/CPAN/Meta/Merge.pm
    version: '2.150010'
  CPAN::Meta::Prereqs:
    file: lib/CPAN/Meta/Prereqs.pm
    version: '2.150010'
  CPAN::Meta::Spec:
    file: lib/CPAN/Meta/Spec.pm
    version: '2.150010'
  CPAN::Meta::Validator:
    file: lib/CPAN/Meta/Validator.pm
    version: '2.150010'
  Parse::CPAN::Meta:
    file: lib/Parse/CPAN/Meta.pm
    version: '2.150010'
requires:
  CPAN::Meta::Requirements: '2.121'
  CPAN::Meta::YAML: '0.011'
  Carp: '0'
  Encode: '0'
  Exporter: '0'
  File::Spec: '0.80'
  JSON::PP: '2.27300'
  Scalar::Util: '0'
  perl: '5.008001'
  strict: '0'
  version: '0.88'
  warnings: '0'
resources:
  bugtracker: https://github.com/Perl-Toolchain-Gang/CPAN-Meta/issues
  homepage: https://github.com/Perl-Toolchain-Gang/CPAN-Meta
  repository: https://github.com/Perl-Toolchain-Gang/CPAN-Meta.git
version: '2.150010'
x_authority: cpan:DAGOLDEN
x_contributors:
  - 'Ansgar Burchardt <ansgar@cpan.org>'
  - 'Avar Arnfjord Bjarmason <avar@cpan.org>'
  - 'Benjamin Noggle <agwind@users.noreply.github.com>'
  - 'Christopher J. Madsen <cjm@cpan.org>'
  - 'Chuck Adams <cja987@gmail.com>'
  - 'Cory G Watson <gphat@cpan.org>'
  - 'Damyan Ivanov <dam@cpan.org>'
  - 'David Golden <xdg@xdg.me>'
  - 'Eric Wilhelm <ewilhelm@cpan.org>'
  - 'Graham Knop <haarg@haarg.org>'
  - 'Gregor Hermann <gregoa@debian.org>'
  - 'Karen Etheridge <ether@cpan.org>'
  - 'Kenichi Ishigaki <ishigaki@cpan.org>'
  - 'Kent Fredric <kentfredric@gmail.com>'
  - 'Ken Williams <kwilliams@cpan.org>'
  - 'Lars Dieckow <daxim@cpan.org>'
  - 'Leon Timmermans <leont@cpan.org>'
  - 'majensen <maj@fortinbras.us>'
  - 'Mark Fowler <markf@cpan.org>'
  - 'Matt S Trout <mst@shadowcat.co.uk>'
  - 'Michael G. Schwern <mschwern@cpan.org>'
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
  - 'mohawk2 <mohawk2@users.noreply.github.com>'
  - 'moznion <moznion@gmail.com>'
  - 'Niko Tyni <ntyni@debian.org>'
  - 'Olaf Alders <olaf@wundersolutions.com>'
  - 'Olivier Mengué <dolmen@cpan.org>'
  - 'Randy Sims <randys@thepierianspring.org>'
  - 'Tomohiro Hosaka <bokutin@bokut.in>'
x_serialization_backend: 'YAML::Tiny version 1.69'
